[package]
name = "under_farm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.69"
walkdir = "2.3.2"
tdlg = { git = "https://github.com/derrickp/tdlg" }
