use super::cell::Cell;
use super::rooms::Room;

pub fn two_by_two_templates() -> Vec<Room> {
    let max_side_length: usize = 4;
    return vec![
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 2),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(3, 1),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 1),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(3, 2),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 2),
                Cell::room_wall(3, 1),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(1, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 2),
                Cell::room_wall(3, 1),
                Cell::room_wall(3, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(2, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 2),
                Cell::room_wall(3, 1),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(1, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 2),
                Cell::room_wall(3, 1),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(0, 1),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 2),
                Cell::room_wall(3, 1),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(0, 2),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 2),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(3, 1),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(1, 3),
                Cell::room_wall(2, 3),
                Cell::splatted_room_wall(3),
                Cell::room_wall(3, 1),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 1),
                // Door
                Cell::room_door(3, 2),
            ],
        },
    ];
}

pub fn three_by_three_templates() -> Vec<Room> {
    let max_side_length: usize = 5;

    return vec![
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(0, 1),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(0, 2),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(0, 3),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(1, 4),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(2, 4),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(3, 4),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(4, 3),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(4, 2),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(4, 1),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(3, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(2, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(1, 4),
                Cell::room_wall(2, 4),
                Cell::room_wall(3, 4),
                Cell::splatted_room_wall(4),
                Cell::room_wall(4, 3),
                Cell::room_wall(4, 2),
                Cell::room_wall(4, 1),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                // Door
                Cell::room_door(1, 0),
            ],
        },
    ];
}

pub fn four_by_four_templates() -> Vec<Room> {
    let max_side_length: usize = 6;

    return vec![
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(0, 1),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(0, 2),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(0, 3),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(0, 4),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(1, 5),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(2, 5),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(3, 5),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(4, 5),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(5, 4),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(5, 3),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(5, 2),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(5, 1),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(4, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(2, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(3, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(3, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(1, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(2, 0),
            ],
        },
        Room {
            max_side_length,
            cells: vec![
                // Walls
                Cell::splatted_room_wall(0),
                Cell::room_wall(0, 1),
                Cell::room_wall(0, 2),
                Cell::room_wall(0, 3),
                Cell::room_wall(0, 4),
                Cell::room_wall(0, 5),
                Cell::room_wall(1, 5),
                Cell::room_wall(2, 5),
                Cell::room_wall(3, 5),
                Cell::room_wall(4, 5),
                Cell::splatted_room_wall(5),
                Cell::room_wall(5, 4),
                Cell::room_wall(5, 3),
                Cell::room_wall(5, 2),
                Cell::room_wall(5, 1),
                Cell::room_wall(5, 0),
                Cell::room_wall(4, 0),
                Cell::room_wall(3, 0),
                Cell::room_wall(2, 0),
                // Floor
                Cell::splatted_room_floor(1),
                Cell::room_floor(1, 2),
                Cell::room_floor(1, 3),
                Cell::room_floor(1, 4),
                Cell::room_floor(2, 1),
                Cell::splatted_room_floor(2),
                Cell::room_floor(2, 3),
                Cell::room_floor(2, 4),
                Cell::room_floor(3, 1),
                Cell::room_floor(3, 2),
                Cell::splatted_room_floor(3),
                Cell::room_floor(3, 4),
                Cell::room_floor(4, 1),
                Cell::room_floor(4, 2),
                Cell::room_floor(4, 3),
                Cell::splatted_room_floor(4),
                // Door
                Cell::room_door(1, 0),
            ],
        },
    ];
}

pub fn all_templates() -> Vec<Room> {
    let mut templates: Vec<Room> = Vec::new();

    templates.append(&mut two_by_two_templates());
    templates.append(&mut three_by_three_templates());
    templates.append(&mut four_by_four_templates());

    return templates;
}
